#!/usr/bin/env python3
"""
Fetch all Ansible Galaxy role records and emit unique GitHub URLs.

Uses the Ansible Galaxy REST API (v1) to paginate through all roles.
Each role record includes github_user and github_repo, which together
form a verified GitHub URL for a known Ansible role.

Usage:
    python3 fetch_galaxy_repo_urls.py --output repo_urls.top100k.txt
    python3 fetch_galaxy_repo_urls.py --output repo_urls.top100k.txt --limit 100000
"""

from __future__ import annotations

import argparse
import sys
import time
import urllib.request
import json
from pathlib import Path

GALAXY_API_URL = "https://galaxy.ansible.com/api/v1/roles/"
PAGE_SIZE = 250
DEFAULT_LIMIT = 100_000
RETRY_MAX = 5
RETRY_DELAY_S = 5


def _fetch_page(url: str) -> dict:
    for attempt in range(1, RETRY_MAX + 1):
        try:
            req = urllib.request.Request(
                url,
                headers={
                    "Accept": "application/json",
                    "User-Agent": "prism-fetcher/1.0",
                },
            )
            with urllib.request.urlopen(req, timeout=30) as resp:
                return json.loads(resp.read().decode())
        except Exception as exc:
            if attempt == RETRY_MAX:
                raise
            print(
                f"  [warn] attempt {attempt} failed ({exc}), retrying in {RETRY_DELAY_S}s…",
                file=sys.stderr,
            )
            time.sleep(RETRY_DELAY_S)
    raise RuntimeError("unreachable")


def fetch_galaxy_urls(limit: int, verbose: bool = True) -> list[str]:
    seen: set[str] = set()
    urls: list[str] = []
    page_url = f"{GALAXY_API_URL}?page_size={PAGE_SIZE}&page=1"
    page_num = 0

    while page_url and len(urls) < limit:
        page_num += 1
        if verbose:
            print(
                f"\r  page {page_num:4d}  collected {len(urls):6d} urls …",
                end="",
                flush=True,
                file=sys.stderr,
            )

        data = _fetch_page(page_url)
        results = data.get("results", [])

        for role in results:
            if len(urls) >= limit:
                break
            github_user = (role.get("github_user") or "").strip()
            github_repo = (role.get("github_repo") or "").strip()
            if not github_user or not github_repo:
                continue
            url = f"https://github.com/{github_user}/{github_repo}"
            if url not in seen:
                seen.add(url)
                urls.append(url)

        # Galaxy API returns absolute next-page URLs
        raw_next = data.get("next") or ""
        # Normalise http → https
        page_url = raw_next.replace("http://", "https://", 1) if raw_next else None

    if verbose:
        print(
            f"\r  done — {len(urls)} unique URLs from {page_num} pages          ",
            file=sys.stderr,
        )

    return urls


def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--output",
        "-o",
        default="repo_urls.top100k.txt",
        help="Output file path (default: repo_urls.top100k.txt)",
    )
    parser.add_argument(
        "--limit",
        "-l",
        type=int,
        default=DEFAULT_LIMIT,
        help=f"Maximum number of URLs to collect (default: {DEFAULT_LIMIT:,})",
    )
    parser.add_argument(
        "--quiet",
        "-q",
        action="store_true",
        help="Suppress progress output",
    )
    args = parser.parse_args()

    output_path = Path(args.output)
    print(
        f"Fetching up to {args.limit:,} Ansible Galaxy role URLs → {output_path}",
        file=sys.stderr,
    )

    urls = fetch_galaxy_urls(limit=args.limit, verbose=not args.quiet)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "# Ansible Galaxy role GitHub URLs — generated by fetch_galaxy_repo_urls.py\n"
        + "\n".join(urls)
        + "\n"
    )

    print(f"Wrote {len(urls):,} URLs to {output_path}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
